<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$checkModule = $request->getModuleName();


/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>
<?php
$header_type = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/header/header_type');
if ($checkModule == 'catalog') {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
    $currentcategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); //get current category
    $baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
    if(!empty($currentcategory->getImageUrl())){
        $catImageUrl = rtrim($baseUrl, '/') . $currentcategory->getImageUrl();
    }else{
        $catImageUrl = $block->getLogoSrc();
    }
   
?>
    <?php if ($block->isHomePage()) : ?>
        <strong class="logo">
        <?php else : ?>
            <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
            <?php endif ?>
            <img src="<?php /* @escapeNotVerified */ echo $catImageUrl ?>" alt="<?php /* @escapeNotVerified */ echo $currentcategory->getName() ?>" <?= $logoWidth ? 'width="' . $block->escapeHtmlAttr($logoWidth) . '"' : '' ?> <?= $logoHeight ? 'height="' . $block->escapeHtmlAttr($logoHeight) . '"' : '' ?> />
            <?php if ($block->isHomePage()) : ?>
        </strong>
    <?php else : ?>
        </a>
    <?php endif ?>
<?php } else { ?>
    <?php if ($block->isHomePage()) : ?>
        <strong class="logo">
        <?php else : ?>
            <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
            <?php endif ?>
            <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>" alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>" <?= $logoWidth ? 'width="' . $block->escapeHtmlAttr($logoWidth) . '"' : '' ?> <?= $logoHeight ? 'height="' . $block->escapeHtmlAttr($logoHeight) . '"' : '' ?> />
            <?php if ($block->isHomePage()) : ?>
        </strong>
    <?php else : ?>
        </a>
    <?php endif ?>
<?php } ?>