<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
$currentcategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

$categoryRepository = $objectManager->create('\Magento\Catalog\Model\CategoryRepository');
$category = $categoryRepository->get($currentcategory->getId());
$subCategories = $category->getChildrenCategories();
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
// $name[] ='';
// print_r($name);
?>

<div class="container mt-2 category-anmolite-mine">
    <div class="row" style="gap: 2%;">
        <h2 class="mt-3 mb-3">COLLECTIONS</h2>
<?php $i = 1; foreach ($subCategories as $cat) { ?>
   
        <div class="col-sm-12" style="margin-bottom: 2%; border:1px solid #b3afaf; height:200px; background-image:url(http://via.placeholder.com/1200x200); background-repeat:round;">
        
            <div class="div-sm-12">
                <span style="font-weight:550;"><?= $cat->getName() ?></span>
            </div>
            <button class="btn btn-success learn-more-button" style="background-color: #9be3be; border: white;"><a style="color:black;" href="<?= $cat->getUrl() ?>">LEARN MORE</a></button>
            <!-- <img src='https://magento-981019-3437920.cloudwaysapps.com/media/porto/placeholder/1200x125.png'/> -->
        </div>    
        
<?php } ?>
<!-- <h5>COLLECTIONS</h5> -->
    </div>
</div>

<style>
    .category-anmolite-mine .learn-more-button{
        position: absolute;
        bottom: 8%;
        left: 8%;
        font-size: 0.75rem !important;
        top: 74%;
        left: 50%;
        -ms-transform: translateX(-50%) translateY(-50%);
        -webkit-transform: translate(-50%,-50%);
        transform: translate(-50%,-50%);
    }
    .category-anmolite-mine .div-sm-12{
        position: absolute;
        font-size: 24px !important;
        color:#17b68d96;
        top: 32%;
        left: 50%;
        -ms-transform: translateX(-50%) translateY(-50%);
        -webkit-transform: translate(-50%,-50%);
        transform: translate(-50%,-50%);
        text-align: center;
    }
    .category-anmolite-mine .mt-3.mb-3{
        color: black;
        font-weight: 600;
    }

</style>