<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->create('\Magento\Store\Model\StoreManagerInterface');
$currentcategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

$categoryRepository = $objectManager->create('\Magento\Catalog\Model\CategoryRepository');
$category = $categoryRepository->get($currentcategory->getId());
$subCategories = $category->getChildrenCategories();
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
// $name[] ='';
// print_r($name);
?>

<div class="container mt-2">
    <div class="row" style="gap: 2%;">

<?php $i = 1; foreach ($subCategories as $cat) {  if ($i <= 2) { ?>
            <div class="col-sm-6" style="border:1px solid #b3afaf; flex: 0 0 49%; height:200px; padding-right: unset; padding-left: unset;">
                <div class="div-sm-6">
                    <span style="font-weight:550;"><a style="color:#17b68d96;" href="<?= $cat->getUrl() ?>"><?= $cat->getName() ?></a></span>
                </div>
                <!-- <img src='https://magento-981019-3437920.cloudwaysapps.com/media/porto/placeholder/590x200.png'/> -->
            </div>
<?php } else { if ($i == 3){ ?><h5 class="mt-3 mb-3">COLLECTIONS</h5><?php } ?>
        <div class="col-sm-12" style="margin-bottom: 2%; border:1px solid #b3afaf; height:125px; background-image:url(https://magento-981019-3437920.cloudwaysapps.com/media/porto/placeholder/1200x125.png); background-repeat:round;">
            <div class="div-sm-12">
                <span style="font-weight:550;"><?= $cat->getName() ?></span>
            </div>
            <button class="btn btn-success learn-more-button" style="background-color: #9be3be; border: white;"><a style="color:black;" href="<?= $cat->getUrl() ?>">LEARN MORE</a></button>
            <!-- <img src='https://magento-981019-3437920.cloudwaysapps.com/media/porto/placeholder/1200x125.png'/> -->
        </div>
<?php } $i++; } ?>
<!-- <h5>COLLECTIONS</h5> -->
    </div>
</div>

<style>
    .learn-more-button{
        position: absolute;
        bottom: 8%;
        left: 8%;
        font-size: 0.75rem !important;
    }
    .div-sm-12{
        position: absolute;
        bottom: 39%;
        left: 8%;
        font-size: 1.00rem !important;
        color:#17b68d96;
    }
    .div-sm-6{
        position: absolute;
        bottom: 39%;
        left: 40%;
        font-size: 1.00rem !important;
        color:#17b68d96;
    }
</style>